### ISSUE TITLE
Fix h-periodic failing deploys

### ISSUE THREAD

**Issue by seanh** [hypothesis/deployment#151]
Examples:

https://jenkins.hypothes.is/job/deployment/5017/

https://jenkins.hypothes.is/job/deployment/5000/

I think if you just deploy it a couple of times you'll see it fail. I've fixed these by terminating the app server and letting it create a new one.

Based on past experience with bouncer I think this may be a bug in the version of Amazon Linux

**Comment by indigobravo** [comment]
A PR has been created to upgrade the version of Linux being used by h-periodic.

**Comment by indigobravo** [comment]
The upgrade to Amazon Linux `Docker running on 64bit Amazon Linux 2/3.2.0` had to be rolled back. The environment simply would not start. I am not sure exactly why, but we have another issue to upgrade Linux version throughout the entire environment: https://github.com/hypothesis/playbook/issues/393. I will add a note to that detailing the problems experienced.

However, one thing I did notice whilst troubleshooting these deploys was the resources that have been allocated to the environments. Prod was running very, very low on resource, and I suspect this was the reason for the deployments essentially timing out.

I have changed the instance type on prod to `t3.micro`, which provides double the resource (2 CPU Cores / 1GB RAM). Since then I have not been able to recreate any problems with deployments failing. I have run three deploys of the latest version through each environment (prod and qa), and all completed successfully. I suspect this was the reason for the failures, but we will have to see how things progress.

```
QA
Start: 0813, Finish: 08:22, Total: 9m23s
Start: 0822, Finish: 08:35, Total: 12m42s
Start: 0835, Finish: 08:45, Total: 9m6s
```
https://jenkins.hypothes.is/job/deployment/5330/
https://jenkins.hypothes.is/job/deployment/5329/
https://jenkins.hypothes.is/job/deployment/5328/


```
PROD
Start: 0849, Finish: 0859:, Total: 9m52s
Start: 0859, Finish: 0909:, Total: 8m42s
Start: 0909, Finish: 0918:, Total: 8m52s
```

https://jenkins.hypothes.is/job/deployment/5333/
https://jenkins.hypothes.is/job/deployment/5332/
https://jenkins.hypothes.is/job/deployment/5331/
